DELETE FROM mydb.Utenti;
ALTER TABLE mydb.Utenti AUTO_INCREMENT = 1;
ALTER TABLE mydb.Poesie AUTO_INCREMENT = 1;
ALTER TABLE mydb.Raccolte AUTO_INCREMENT = 1;
ALTER TABLE mydb.Report AUTO_INCREMENT = 1;
ALTER TABLE mydb.Commenti AUTO_INCREMENT = 1;
ALTER TABLE mydb.Apprezzamenti AUTO_INCREMENT = 1;
ALTER TABLE mydb.ProfiliPersonali AUTO_INCREMENT = 1;